version: '3.4'

services:
  backend:
    container_name: app
    build: ./be
    volumes:
      - .:/usr/src/app
    ports:
      - 80:5000
    links:
      - db
  db:
    build: ./db
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3305:3306
    environment:
      MYSQL_ROOT_PASSWORD: password