FROM python:3.7

LABEL maintainer="meetwithfriendsapp@gmail.com"

WORKDIR /usr/src/app 

COPY requirements.txt ./
RUN pip3 install --no-cache-dir -r requirements.txt

RUN ls

COPY . .
RUN ls
EXPOSE 5000

CMD [ "python3", "be/run.py" ]

