FROM python:3

LABEL maintainer="meetwithfriendsapp@gmail.com"

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD [ "python3", "be/auth.py" ]